[package]
disabled = true

[nodejs]

[ruby]
disabled = true

[cmd_duration]

[hostname]
ssh_only = false

[php]

[username]
show_always = false

[directory.substitutions]
"~" = 'ğŸ '

[shell]
disabled = false

[container]
disabled = true

[character]
success_symbol = '[âœ](bold green) '
error_symbol = '[âœ—](bold red) '
